version: '3.8'
services:
  appointmet-api:
    container_name: aware-appointment-api
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: aware-appointment-api:latest
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      PSQL_HOST: db
      REDIS_HOST: redis
    depends_on:
      - db
      - redis

  db:
    container_name: postgres-auction-api
    image: postgres:15.3
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=api
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    env_file:
      - .env
    environment:
      - REDIS_API_HOST=localhost
      - REDIS_API_PORT=6379
      - REDIS_API_DB=3
